development: &default
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'localhost'
  port: '9200'
  version: '6.5'
test:
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'localhost'
  port: '9300'
  version: '6.5'
staging:
  <<: *default
production:
  es_bin: '/usr/share/elasticsearch/bin/elasticsearch'
  host: 'localhost:9400'
  port: '9400'