development: &default
  es_bin: 'path/to/elasticsearch/file/on/bin/path'
  host: host
  port: port
  version: x.x.x
test:
  es_bin: 'path/to/elasticsearch/file/on/bin/path'
  host: host
  port: port
  version: x.x.x
staging:
  <<: *default
production:
  es_bin: 'path/to/elasticsearch/file/on/bin/path'
  host: host
  port: port
  version: x.x.x