development:
  DATABASE_USERNAME: developer
  DATABASE_PASSWORD: secure_password
  DATABASE_HOST: localhost
  CORS_ORIGINS: http://localhost:5000
test:
  DATABASE_USERNAME: developer
  DATABASE_PASSWORD: secure_password
  DATABASE_HOST: localhost
  CORS_ORIGINS: http://localhost:5000
production:
  DATABASE_USERNAME: developer
  DATABASE_PASSWORD: secure_password
  DATABASE_HOST: localhost
  ELASTICSEARCH_URL: http://localhost:9200
deployment:
  APP_NAME: SwApi
  DEPLOY_USER:
  DEPLOY_HOST:
  DEPLOY_PASS:
  DEPLOY_URL: git@github.com:cpetersen223/sw-api.git